// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1dHNP1_ftcrcqr3e-ehVj5hnj_W5kYUU',
    appId: '1:123162346817:web:7fcc37d93ca727d4780dc0',
    messagingSenderId: '123162346817',
    projectId: 'fir-getx-app-debdd',
    authDomain: 'fir-getx-app-debdd.firebaseapp.com',
    storageBucket: 'fir-getx-app-debdd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvaeRdHRdv8sBVEKSZhfDUGywLVOC-c8U',
    appId: '1:123162346817:android:3b00a1698c7d7459780dc0',
    messagingSenderId: '123162346817',
    projectId: 'fir-getx-app-debdd',
    storageBucket: 'fir-getx-app-debdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtxrYCYkzKoByNmVuLkP0BaQEVl7e6J90',
    appId: '1:123162346817:ios:faa58d359411934d780dc0',
    messagingSenderId: '123162346817',
    projectId: 'fir-getx-app-debdd',
    storageBucket: 'fir-getx-app-debdd.appspot.com',
    iosClientId: '123162346817-6qr76qp08upe1r66lsnje75v5dovhrs4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtxrYCYkzKoByNmVuLkP0BaQEVl7e6J90',
    appId: '1:123162346817:ios:ec326f7e373dbad5780dc0',
    messagingSenderId: '123162346817',
    projectId: 'fir-getx-app-debdd',
    storageBucket: 'fir-getx-app-debdd.appspot.com',
    iosClientId: '123162346817-e7c4un70n7gtbjcjui4hvmf1euotajqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
